version: '3.7'

services:

  fastapi:
    build: ./fastapi
    ports:
      - 80:80

  prom:
    image: prom/prometheus:v2.27.1
    ports:
      - 9090:9090
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom/rules.yml:/etc/prometheus/rules.yml
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    volumes: 
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini

volumes:
  prometheus_data: {}

networks:
  default:
    name: metrics-network